package com.holo.support.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.holo.support.bean.DemoBean;
import com.holo.support.bean.LoginBean;

import com.holo.support.dao.DemoBeanDao;
import com.holo.support.dao.LoginBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig demoBeanDaoConfig;
    private final DaoConfig loginBeanDaoConfig;

    private final DemoBeanDao demoBeanDao;
    private final LoginBeanDao loginBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        demoBeanDaoConfig = daoConfigMap.get(DemoBeanDao.class).clone();
        demoBeanDaoConfig.initIdentityScope(type);

        loginBeanDaoConfig = daoConfigMap.get(LoginBeanDao.class).clone();
        loginBeanDaoConfig.initIdentityScope(type);

        demoBeanDao = new DemoBeanDao(demoBeanDaoConfig, this);
        loginBeanDao = new LoginBeanDao(loginBeanDaoConfig, this);

        registerDao(DemoBean.class, demoBeanDao);
        registerDao(LoginBean.class, loginBeanDao);
    }
    
    public void clear() {
        demoBeanDaoConfig.clearIdentityScope();
        loginBeanDaoConfig.clearIdentityScope();
    }

    public DemoBeanDao getDemoBeanDao() {
        return demoBeanDao;
    }

    public LoginBeanDao getLoginBeanDao() {
        return loginBeanDao;
    }

}
